### ISSUE TITLE
Unable to clone

### ISSUE THREAD

**Issue by kmiit** [krypton-byte/chrome-termux#1]
Hey,sir.I would like to run chrome browser in termux without a container and I am very interested in this repository. But I cannot use git lfs to clone it because of bindwith limition. I also tried to compile chromium by myself,but it doesn't work in termux at all(maybe the reason of symbol library).Could you give me a copy of chrome.tar.gz of this repository or give me some guides on compiling it? Tks. (Sorry for my poor English)

**Comment by krypton-byte** [comment]
Yeah, if it doesn't work you can try my chrome browser, here https://www.mediafire.com/file/8kbu4daavnkuaf5/chrome.tar%255B1%255D.gz/file, if there any problem, let me know

**Comment by kmiit** [comment]
Thanks very much for your help. It works very well in termux both in desktop mode and headless mode though throws some errors. Helped me a lot.(I replied to the github email before closing this issue, but it seems to have no effect)

**Comment by ZefianAlfian** [comment]
Hi, Do you have a new version chrome browser for termux? or teach me how make it?

**Comment by kmiit** [comment]
> Hi, Do you have a new version chrome browser for termux? or teach me how make it?

```bash
pkg up
pkg i tur-repo
pkg i chromium
```
